# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hde-ghel <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/07 18:49:22 by hde-ghel          #+#    #+#              #
#    Updated: 2018/10/08 20:08:53 by hde-ghel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = ft_display_file.c
FALG = -Wall -Wextra -Werror
OBJ = ft_display_file.o

all : $(NAME)

$(NAME) :
	gcc -c $(FLAG) $(SRC)
	gcc -o $(NAME) $(OBJ)

clean :
	/bin/rm -f $(OBJ)

fclean : clean
	/bin/rm -f $(NAME) $(OBJ)
